# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907cf9b44363eefd7cd8f12d99c0597817e18c2df3140515a38a2399074d673d600953b1a95180a30946d71267432bff09991844d7c7208035829fb42ab929ae

test:
  secret_key_base: cc758ccd0c4db8d948eddee262ebc4850cd7d6f926615765c4a0345ac468f33a2100ebd4e0e92372c6471157d7c984fb7b2ff82ba5fd04971148736c75dcaba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
